### ISSUE TITLE
0.25.x fails to build using rust older than 1.81

### ISSUE THREAD

**Issue by SanjoDeundiak** [twittner/minicbor#2]
I'm trying to build the library but it fails while using anything older that the latest stable (1.81) due to `error_in_core` unstable feature. Is that intended? Would be cool to support at least few versions back.

**Comment by twittner** [comment]
Yes, the main motivation for 0.25 was the switch to `core::error::Error`. To cause not too many problems I used a larger version bump. Feel to wait with the upgrade. So far there is not too much in 0.25.
